"""初始模型

Revision ID: 7da410d75d4c
Revises: 
Create Date: 2026-03-04 17:14:49.223819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da410d75d4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='文章的唯一标识'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='文章标题'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='编写文章的用户'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='文章id'),
    sa.Column('content', sa.Text(), nullable=False, comment='文章内容'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='分类id'),
    sa.Column('category_name', sa.String(length=100), nullable=False, comment='分类标题'),
    sa.Column('category_user_id', sa.Integer(), nullable=False, comment='创建用户的id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False, comment='友链id'),
    sa.Column('links', sa.String(length=100), nullable=False, comment='网站名称'),
    sa.Column('href', sa.String(length=2000), nullable=False, comment='网站链接'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户唯一id'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='用户名字'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='用户邮箱'),
    sa.Column('password_hash', sa.String(length=258), nullable=False, comment='用户密码'),
    sa.Column('avatar', sa.String(length=100), nullable=True, comment='用户头像路径'),
    sa.Column('bio', sa.String(length=1000), nullable=True, comment='用户个人简介'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='用户注册时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('links')
    op.drop_table('category')
    op.drop_table('blog')
    # ### end Alembic commands ###
